---
# Argo CD App definition for cluster1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster1
spec:
  destination:
    server: linode-production
    namespace: default
  project: kubecon-demo
  source:
    path: deploy/overlays/cluster1
    repoURL: https://github.com/qingkunl/argocd-app-of-apps-demo.git
    targetRevision: HEAD
---
