---
# Argo CD App definition for cluster1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster1
spec:
  destination:
    server: https://a9821dc8-35ae-4fa9-a721-be8bf6f46ffd.ap-south-2.linodelke.net:443
    namespace: default
  project: demo-parent
  source:
    path: deploy/overlays/cluster1
    repoURL: https://github.com/chaoyinloong/argocdapps.git
    targetRevision: HEAD
---
